"""
Decodifica delle divisioni ATECO 2007 (convenzione INAIL, 2 cifre).

Fonte: INAIL, "Tabelle nazionali con cadenza semestrale", Tabella B1.1.2
(Classificazione delle attività economiche ATECO 2007, Istat Metodi e norme n. 40, 2009).
Usata dall'ETL multidimensionale per mostrare il nome del settore associato
a ciascuna divisione (es. "H 52" -> "Magazzinaggio e attività di supporto ai trasporti").
"""

ATECO_DIVISIONI: dict[str, str] = {
    "A 01": "Agricoltura, silvicoltura e pesca",
    "A 02": "Silvicoltura ed utilizzo di aree forestali",
    "A 03": "Pesca e acquacoltura",
    "B 06": "Estrazione di minerali da cave e miniere",
    "B 08": "Industrie estrattive",
    "B 09": "Attività di supporto all'estrazione",
    "C 10": "Industrie alimentari",
    "C 11": "Industria delle bevande",
    "C 12": "Industria del tabacco",
    "C 13": "Industrie tessili",
    "C 14": "Confezione di articoli di abbigliamento",
    "C 15": "Fabbricazione di articoli in pelle e simili",
    "C 16": "Industria del legno e prodotti in legno e sughero",
    "C 17": "Fabbricazione di carta e prodotti di carta",
    "C 18": "Stampa e riproduzione di supporti registrati",
    "C 19": "Fabbricazione di coke e prodotti della raffinazione del petrolio",
    "C 20": "Fabbricazione di prodotti chimici",
    "C 21": "Fabbricazione di prodotti farmaceutici di base e preparati farmaceutici",
    "C 22": "Fabbricazione di articoli in gomma e materie plastiche",
    "C 23": "Fabbricazione di altri prodotti della lavorazione di minerali non metalliferi",
    "C 24": "Metallurgia",
    "C 25": "Fabbricazione di prodotti in metallo (esclusi macchinari e attrezzature)",
    "C 26": "Fabbricazione di computer, prodotti di elettronica e ottica",
    "C 27": "Fabbricazione di apparecchiature elettriche e per uso domestico non elettriche",
    "C 28": "Fabbricazione di macchinari ed apparecchiature n.c.a.",
    "C 29": "Fabbricazione di autoveicoli, rimorchi e semirimorchi",
    "C 30": "Fabbricazione di altri mezzi di trasporto",
    "C 31": "Fabbricazione di mobili",
    "C 32": "Altre industrie manifatturiere",
    "C 33": "Riparazione, manutenzione ed installazione di macchine ed apparecchiature",
    "D 35": "Fornitura di energia elettrica, gas, vapore e aria condizionata",
    "E 36": "Raccolta, trattamento e fornitura di acqua",
    "E 37": "Gestione delle reti fognarie",
    "E 38": "Attività di gestione dei rifiuti e risanamento",
    "E 39": "Risanamento e altri servizi di gestione dei rifiuti",
    "F 41": "Costruzione di edifici",
    "F 42": "Ingegneria civile",
    "F 43": "Lavori di costruzione specializzati",
    "G 45": "Commercio all'ingrosso e al dettaglio e riparazione di autoveicoli e motocicli",
    "G 46": "Commercio all'ingrosso",
    "G 47": "Commercio al dettaglio",
    "H 49": "Trasporto terrestre e trasporto mediante condotte",
    "H 50": "Trasporto via acqua",
    "H 51": "Trasporto aereo",
    "H 52": "Magazzinaggio e attività di supporto ai trasporti",
    "H 53": "Attività postali e di corriere",
    "I 55": "Alloggio",
    "I 56": "Attività dei servizi di ristorazione",
    "J 58": "Attività editoriali",
    "J 59": "Produzione cinematografica, video, musicale e programmi televisivi",
    "J 60": "Attività di programmazione e trasmissione",
    "J 61": "Telecomunicazioni",
    "J 62": "Produzione di software e consulenza informatica",
    "J 63": "Attività dei servizi di informazione",
    "K 64": "Attività di servizi finanziari (escluse assicurazioni e fondi pensione)",
    "K 65": "Assicurazioni, riassicurazioni e fondi pensione",
    "K 66": "Attività ausiliarie dei servizi finanziari e delle assicurazioni",
    "L 68": "Attività immobiliari",
    "M 69": "Attività legali e contabilità",
    "M 70": "Attività di studi di architettura e ingegneria",
    "M 71": "Attività di ricerca scientifica e sviluppo",
    "M 72": "Attività professionali, scientifiche e tecniche",
    "M 73": "Pubblicità e ricerche di mercato",
    "M 74": "Altre attività professionali, scientifiche e tecniche",
    "M 75": "Servizi veterinari",
    "N 77": "Attività di noleggio e leasing operativo",
    "N 78": "Attività di ricerca, selezione e fornitura di personale",
    "N 79": "Agenzie di viaggio e servizi di prenotazione",
    "N 80": "Servizi di vigilanza e investigazione",
    "N 81": "Servizi di supporto per le imprese",
    "N 82": "Servizi di supporto alle imprese n.c.a.",
    "O 84": "Pubblica amministrazione e difesa, assicurazione sociale obbligatoria",
    "P 85": "Istruzione",
    "Q 86": "Assistenza sanitaria",
    "Q 87": "Servizi di assistenza sociale residenziale",
    "Q 88": "Assistenza sociale non residenziale",
    "R 90": "Attività creative, artistiche e di intrattenimento",
    "R 91": "Attività di biblioteche, archivi, musei e altre attività culturali",
    "R 92": "Attività di gioco e scommesse",
    "R 93": "Attività sportive, di intrattenimento e divertimento",
    "S 94": "Attività di associazioni e organizzazioni",
    "S 95": "Riparazione di computer e beni per uso personale e per la casa",
    "S 96": "Altre attività di servizi",
    "T 97": "Attività di famiglie e convivenze come datori di lavoro per personale domestico",
    "T 98": "Produzione di beni e servizi indifferenziati per uso proprio da parte di famiglie",
    "U 99": "Organizzazioni ed organismi extraterritoriali",
}

# Sezione ATECO per ogni codice (macro): usata per raggruppare le divisioni
ATECO_MACRO_NAMES: dict[str, str] = {
    "A": "Agricoltura, silvicoltura e pesca",
    "B": "Estrazione di minerali da cave e miniere",
    "C": "Attività manifatturiere",
    "D": "Fornitura di energia elettrica, gas, vapore e aria condizionata",
    "E": "Acqua, reti fognarie, rifiuti e risanamento",
    "F": "Costruzioni",
    "G": "Commercio all'ingrosso e al dettaglio, riparazione autoveicoli",
    "H": "Trasporto e magazzinaggio",
    "I": "Attività dei servizi di alloggio e ristorazione",
    "J": "Servizi di informazione e comunicazione",
    "K": "Attività finanziarie e assicurative",
    "L": "Attività immobiliari",
    "M": "Attività professionali, scientifiche e tecniche",
    "N": "Noleggio, agenzie di viaggio, servizi di supporto alle imprese",
    "O": "Amministrazione pubblica e difesa, assicurazione sociale obbligatoria",
    "P": "Istruzione",
    "Q": "Sanità e assistenza sociale",
    "R": "Attività artistiche, sportive, di intrattenimento e divertimento",
    "S": "Altre attività di servizi",
    "T": "Famiglie e convivenze come datori di lavoro per personale domestico",
    "U": "Organizzazioni ed organismi extraterritoriali",
}